#此工作流将使用Maven构建包，然后在创建发布时将其发布到GitHub包
#有关更多信息，请参阅：https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

姓名:Maven包

在……之上:
释放:
类型:[创造]

工作:
建立:

run-on:ubuntu-最新
权限:
内容:读
包:写

步骤:
-uses:操作/结帐@v4
-姓名:设置JDK11
uses:操作/设置-java@v4
和……一起:
java版:'11'
分布:'temurin'
server-id:GitHub#pom.xml的distributionManagement/repository/id字段的值
设置-路径:${{github.workspace}} #settings.xml文件的位置

-姓名:使用Maven构建
跑:mvn-B包--file pom.xml

-姓名:发布到GitHub包Apache Maven
跑:mvn deploy-s$GITHUB_WORKSPACE/settings.xml
env:
GitHub_TOKEN:${{github.token}}
